"""initial schema

Revision ID: 98969585789d
Revises: 
Create Date: 2026-04-17 22:36:58.502621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98969585789d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('machine_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('sensor_id', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_machine_id'), ['machine_id'], unique=False)

    op.create_table('failure_predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('machine_name', sa.String(length=255), nullable=False),
    sa.Column('predicted_failure_at', sa.DateTime(), nullable=False),
    sa.Column('estimated_hours_remaining', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('failure_type', sa.String(length=255), nullable=False),
    sa.Column('urgency', sa.String(length=50), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('assigned_technician_id', sa.String(), nullable=True),
    sa.Column('assigned_technician_name', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('auto_work_order_id', sa.String(), nullable=True),
    sa.Column('notified_72h', sa.Boolean(), nullable=False),
    sa.Column('notified_48h', sa.Boolean(), nullable=False),
    sa.Column('notified_24h', sa.Boolean(), nullable=False),
    sa.Column('notified_12h', sa.Boolean(), nullable=False),
    sa.Column('notified_6h', sa.Boolean(), nullable=False),
    sa.Column('notified_1h', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('failure_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_failure_predictions_machine_id'), ['machine_id'], unique=False)

    op.create_table('machines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('install_date', sa.String(length=50), nullable=False),
    sa.Column('next_maintenance_date', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('firmware_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('machine_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scheduled_date', sa.String(length=50), nullable=False),
    sa.Column('completed_date', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('parts_replaced', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_records_machine_id'), ['machine_id'], unique=False)

    op.create_table('sensors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=False),
    sa.Column('max_threshold', sa.Float(), nullable=False),
    sa.Column('critical_min', sa.Float(), nullable=False),
    sa.Column('critical_max', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_machine_id'), ['machine_id'], unique=False)

    op.create_table('technicians',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('shift_start_hour', sa.Integer(), nullable=False),
    sa.Column('shift_end_hour', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('current_assignment_machine_id', sa.String(), nullable=True),
    sa.Column('current_assignment_machine_name', sa.String(length=255), nullable=True),
    sa.Column('assignment_started_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_free_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technicians_email'), ['email'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technicians_email'))

    op.drop_table('technicians')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_machine_id'))

    op.drop_table('sensors')
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_records_machine_id'))

    op.drop_table('maintenance_records')
    op.drop_table('machines')
    with op.batch_alter_table('failure_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_failure_predictions_machine_id'))

    op.drop_table('failure_predictions')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_machine_id'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
